version: "3.9"

services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server

  customer-db:
    image: postgres:16
    container_name: customer-db
    environment:
      POSTGRES_DB: digibank_customer_db
      POSTGRES_USER: digibankuser
      POSTGRES_PASSWORD: digibankpwd
    ports:
      - "5433:5432"
    volumes:
      - customer_data:/var/lib/postgresql/data

  account-db:
    image: postgres:16
    container_name: account-db
    environment:
      POSTGRES_DB: digibank_account_db
      POSTGRES_USER: digibankuser
      POSTGRES_PASSWORD: digibankpwd
    ports:
      - "5434:5432"
    volumes:
      - account_data:/var/lib/postgresql/data

  transaction-db:
    image: postgres:16
    container_name: transaction-db
    environment:
      POSTGRES_DB: digibank_transaction_db
      POSTGRES_USER: digibankuser
      POSTGRES_PASSWORD: digibankpwd
    ports:
      - "5435:5432"
    volumes:
      - transaction_data:/var/lib/postgresql/data

  compliance-db:
    image: postgres:16
    container_name: compliance-db
    environment:
      POSTGRES_DB: digibank_compliance_db
      POSTGRES_USER: digibankuser
      POSTGRES_PASSWORD: digibankpwd
    ports:
      - "5436:5432"
    volumes:
      - compliance_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: digibank_notification_db
      POSTGRES_USER: digibankuser
      POSTGRES_PASSWORD: digibankpwd
    ports:
      - "5437:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
      - discovery-server

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - account-db
      - discovery-server

  compliance-service:
    build: ./compliance-service
    ports:
      - "8084:8084"
    depends_on:
      - compliance-db

  notification-service:
    build: ./notification-service
    ports:
      - "8085:8085"
    depends_on:
      - notification-db

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - transaction-db
      - discovery-server
      - account-service
      - compliance-service
      - notification-service

volumes:
  customer_data:
  account_data:
  transaction_data:
  compliance_data:
  notification_data:
